!                           DISCLAIMER
! 
!   This file was generated by TAF version 4.0.3
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 
module     constants
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare parameters
!==============================================
real, parameter :: c_days_per_year = 365.0
real, parameter :: c_deg2dist = 111194.9
real, parameter :: c_pi = 3.14159265358979
real, parameter :: c_deg2rad = c_pi/180.0
integer, parameter :: c_error_message_unit = 15
integer, parameter :: c_max_len_filename = 512
integer, parameter :: c_model_data_unit = 14
real, parameter :: c_rad2deg = 1.0/c_deg2rad
real, parameter :: c_sec2rad = c_deg2rad/3600.0
real, parameter :: c_seconds_per_day = 86400.0
integer, parameter :: c_standard_message_unit = 6

end module     constants

module     cost1dparameters
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare parameters
!==============================================
integer, parameter :: cp_iann = 3
integer, parameter :: cp_iapln = 3
integer, parameter :: cp_iaug = 2
integer, parameter :: cp_idiv_heddy = 2
integer, parameter :: cp_ifeb = 1
integer, parameter :: cp_iheddy = 1
integer, parameter :: cp_inetlwpln = 5
integer, parameter :: cp_inetswpln = 4
integer, parameter :: cp_isolin = 1
integer, parameter :: cp_itsfc = 6
integer, parameter :: cp_iyice_n = 2
integer, parameter :: cp_iyice_s = 1
integer, parameter :: cp_nlongtermperiods = 3
integer, parameter :: cv_nlongtermmeans = 2
integer, parameter :: cv_nlongtermmeanstgrid = 6
integer, parameter :: cv_nlongtermmeansugrid = 1

!==============================================
! declare local variables
!==============================================
real :: cp_lastinterval
real :: cp_longitudebeg(1:cp_nlongtermperiods)
real :: cp_longitudeend(1:cp_nlongtermperiods)

end module     cost1dparameters

module     sizes
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare parameters
!==============================================
integer, parameter :: jmt = 20

end module     sizes

module     cost1dvariables
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes
use cost1dparameters

implicit none

!==============================================
! declare local variables
!==============================================
real :: cv_longtermmeans(1:cp_nlongtermperiods,1:cv_nlongtermmeans)
real :: cv_longtermmeanstgrid(1:jmt,1:cp_nlongtermperiods,1:cv_nlongtermmeanstgrid)
real :: cv_longtermmeanstgrid_ad(1:jmt,1:cp_nlongtermperiods,1:cv_nlongtermmeanstgrid)
real :: cv_longtermmeansugrid(1:jmt,1:cp_nlongtermperiods,1:cv_nlongtermmeansugrid)
real :: cv_longtermtimes(1:cp_nlongtermperiods)
real :: cv_seasonbeg(1:cp_nlongtermperiods)
real :: cv_seasonend(1:cp_nlongtermperiods)

contains
subroutine cost1dvariables_constructor_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
cv_longtermmeanstgrid_ad(:,:,:) = 0.

end subroutine cost1dvariables_constructor_ad
end module     cost1dvariables

module     ebm1dgrids
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes

implicit none

!==============================================
! declare local variables
!==============================================
real :: eg_cst(1:jmt)
real :: eg_csu(1:jmt)
real :: eg_dxt
real :: eg_dxu
real :: eg_dyt(1:jmt)
real :: eg_dyu(1:jmt)
integer :: eg_jmt
real :: eg_sint(1:jmt)
real :: eg_sinu(1:jmt)
real :: eg_yt(1:jmt)
real :: eg_yu(1:jmt)

end module     ebm1dgrids

module     ebm1dparameters
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes
use constants

implicit none

!==============================================
! declare local variables
!==============================================
real :: ep_aice
real :: ep_alw
real :: ep_alw_ad
real :: ep_alwbak
real :: ep_alwerr
real :: ep_apln0
real :: ep_apln1
real :: ep_apln2
real :: ep_blw
real :: ep_blw_ad
real :: ep_blwbak
real :: ep_blwerr
real :: ep_clipr
real :: ep_co2ccn
real :: ep_co2ref
real :: ep_cp0
real :: ep_diff0
real :: ep_diff0_ad
real :: ep_diff0bak
real :: ep_diff0err
real :: ep_diff2
real :: ep_diff2_ad
real :: ep_diff2bak
real :: ep_diff2err
real :: ep_diff4
real :: ep_diff4_ad
real :: ep_diff4bak
real :: ep_diff4err
real :: ep_dqco2x2
real :: ep_dqco2x2_ad
real :: ep_dqco2x2bak
real :: ep_dqco2x2err
real :: ep_eccen
real :: ep_fland(1:jmt)
real :: ep_focean(1:jmt)
character(len=c_max_len_filename) :: ep_fraccloudfilename
character(len=c_max_len_filename) :: ep_fraclandfilename
character(len=c_max_len_filename) :: ep_gridfilename
real :: ep_hcrat
real :: ep_hocn
real :: ep_hocn_ad
real :: ep_hocnbak
real :: ep_hocnerr
real :: ep_obliq
real :: ep_perih
real :: ep_perihp
real :: ep_pyear
real :: ep_rhowat
real :: ep_scon0
real :: ep_tcrit
logical :: ep_useicealbedofeedback

contains
subroutine ebm1dparameters_constructor_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
ep_alw_ad = 0.
ep_blw_ad = 0.
ep_diff0_ad = 0.
ep_diff2_ad = 0.
ep_diff4_ad = 0.
ep_dqco2x2_ad = 0.
ep_hocn_ad = 0.

end subroutine ebm1dparameters_constructor_ad
end module     ebm1dparameters

module     ebm1dvariables
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes

implicit none

!==============================================
! declare local variables
!==============================================
real :: ev_apln(1:jmt)
real :: ev_apln_ad(1:jmt)
real :: ev_apln_icefree(1:jmt)
real :: ev_ceff
real :: ev_ceff_ad
real :: ev_cosz(1:jmt)
real :: ev_deltatbeg
real :: ev_deltatend
real :: ev_diff_cnt(1:jmt)
real :: ev_diff_cnt_ad(1:jmt)
real :: ev_div_heddy(1:jmt)
real :: ev_div_heddy_ad(1:jmt)
real :: ev_heddy(1:jmt)
real :: ev_heddy_ad(1:jmt)
integer :: ev_jice_n
integer :: ev_jice_s
real :: ev_lambda
real :: ev_lambdap
real :: ev_netlwpln(1:jmt)
real :: ev_netlwpln_ad(1:jmt)
real :: ev_netswpln(1:jmt)
real :: ev_netswpln_ad(1:jmt)
real :: ev_solin(1:jmt)
real :: ev_tsfc(1:jmt)
real :: ev_tsfc_ad(1:jmt)
real :: ev_yice_n
real :: ev_yice_s

contains
subroutine ebm1dvariables_constructor_ad()
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
ev_apln_ad(:) = 0.
ev_ceff_ad = 0.
ev_diff_cnt_ad(:) = 0.
ev_div_heddy_ad(:) = 0.
ev_heddy_ad(:) = 0.
ev_netlwpln_ad(:) = 0.
ev_netswpln_ad(:) = 0.
ev_tsfc_ad(:) = 0.

end subroutine ebm1dvariables_constructor_ad
end module     ebm1dvariables

module     initialconditions
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes

implicit none

!==============================================
! declare local variables
!==============================================
real :: ic_tsfc(1:jmt)

end module     initialconditions

module     observations
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes
use cost1dparameters

implicit none

!==============================================
! declare local variables
!==============================================
real :: ob_tsfc(1:jmt,1:cp_nlongtermperiods)

end module     observations

module     optimizationparameters
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare parameters
!==============================================
integer, parameter :: nmax = 10

!==============================================
! declare local variables
!==============================================
real :: cond(1:nmax)

end module     optimizationparameters

module     orbparameters
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use constants

implicit none

!==============================================
! declare parameters
!==============================================
integer, parameter :: nef = 19
integer, parameter :: neff = 19
integer, parameter :: nob = 47
integer, parameter :: nobb = 47
integer, parameter :: nop = 78
integer, parameter :: nopp = 78
real, parameter :: prm = 50.439273
real, parameter :: xod = 23.320556
real, parameter :: xop = 3.392506

!==============================================
! declare local variables
!==============================================
real :: ae(nef)
real :: aob(nob)
real :: aop(nop)
real :: be(nef)
real :: bob(nob)
real :: bop(nop)
real :: ce(nef)
real :: cob(nob)
real :: cop(nop)
real :: op_eccen
real :: op_latit
real :: op_obliq
real :: op_perih
real :: op_scon0

end module     orbparameters

module     referencedata
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use sizes
use cost1dparameters

implicit none

!==============================================
! declare local variables
!==============================================
real :: rf_tsfc(1:jmt,1:cp_nlongtermperiods)

end module     referencedata

module     runparameters
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 4.0.3   **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use constants

implicit none

!==============================================
! declare local variables
!==============================================
real :: rp_deltat
real :: rp_endtime
character(len=c_max_len_filename) :: rp_initialconditionsfilename
integer :: rp_myiter
real :: rp_mytime
integer :: rp_ntimesteps
character(len=c_max_len_filename) :: rp_observationsfilename
character(len=c_max_len_filename) :: rp_referencedatafilename
character(len=c_max_len_filename) :: rp_restartdatafilename
real :: rp_starttime

end module     runparameters
